# This file assumes that the bashrc file that comes with
# excentury has been sourced.

export XCPP_CONFIG_PATH=$XCROOT/main

export PATH=$XCROOT/main/bin:$PATH
export LD_LIBRARY_PATH=$XCROOT/main/lib:$LD_LIBRARY_PATH
export MMA_PATH=$XCROOT/main/mathematica:$MMA_PATH
export PYTHONPATH=$XCROOT/main/python:$PYTHONPATH
export MATLABPATH=$XCROOT/main/matlab:$MATLABPATH
